Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -20,4 +20,12 @@ jobs:
       run: |
         chmod +x docker/check/check.sh
         docker-compose -f docker/check/docker-compose.yml up --build
+    - name: Check container status
+      run: |
+        exit_status=$(docker inspect check_pandoc_1 --format='{{.State.ExitCode}}')
+        if [ "$exit_status" != "0" ]; then
+          echo "Container exited with error code $exit_status"
+          exit $exit_status
+        fi
+    
 
